name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install g++
    - name: Compile C++ code
      run: g++ -o output main.cpp
    - name: Run the program
      run: ./output
